### ISSUE TITLE
Could not use multiGPU

### ISSUE THREAD

**Issue by ParanoidW** [ElephantGit/FPN-for-Semantic-Segmentation#1]
Actually, the current version doesn't support multiGPU in train_val.py.

**Comment by ElephantGit** [comment]
what the command line do you use to us multiGPUs?

**Comment by ParanoidW** [comment]
> what the command line do you use to us multiGPUs?

`python train_val.py --dataset Cityscapes --save_dir /path/to/run --mGPUs True --gpu_ids 0,1,2`
Just followed the README. However, the train_val.py doesn't support mGPUs and gpu_ids arguments.

**Comment by ElephantGit** [comment]
how many gpus do you have? three?

**Comment by ParanoidW** [comment]
I have 8 in total and have tested on 3.

**Comment by ElephantGit** [comment]
Emmm, could you copy your error message here?

**Comment by ParanoidW** [comment]
It tells me that the parser can't parse mGPUs and gpu_ids.

**Comment by ElephantGit** [comment]
sorry, this is my fault, recent commit cover the mGPUs version code. This version does not support mGPUs training.

**Comment by ParanoidW** [comment]
Thanks anyway~

**Comment by ElephantGit** [comment]
I roll-back the recent commit, you can try now to see whether it work now.
